// Build-time config injector.
// Generates a tiny runtime config file that the frontend can read to discover the
// correct API base URL (handles cross-subdomain deployments, local dev, preview envs).

const fs = require('fs');
const path = require('path');

const API_BASE = process.env.API_BASE || process.env.VITE_API_BASE || '';
const APP_VERSION = process.env.APP_VERSION || require('../package.json').version;
const ENV_NAME = process.env.ENV_NAME || 'production';

const config = {
  API_BASE,
  APP_VERSION,
  ENV_NAME,
  BUILD_TIME: new Date().toISOString()
};

const out = `// AUTO-GENERATED by scripts/build-config.js — do not edit.
window.__GSM_CONFIG__ = Object.freeze(${JSON.stringify(config, null, 2)});
`;

const destDir = path.resolve(__dirname, '..', 'dist');
if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
fs.writeFileSync(path.join(destDir, 'config.js'), out, 'utf8');

console.log('[build-config] Generated dist/config.js');
console.log('[build-config] API_BASE =', API_BASE || '(relative — same origin)');
console.log('[build-config] APP_VERSION =', APP_VERSION);
console.log('[build-config] ENV_NAME =', ENV_NAME);
